modLoader = "javafml"
loaderVersion = "[47,)"
license = "ARR"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = "${mod_description}"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "civil"
mandatory = true
versionRange = "[${civillis_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ftblibrary"
mandatory = false
versionRange = "[2001.2.10,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ftbchunks"
mandatory = false
versionRange = "[2001.3.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "civil_custom_regions.mixins.json"
